### ISSUE TITLE
filter to exclude an ip address or port?

### ISSUE THREAD

**Issue by aradford123** [cisco/joy#10]
Is it possible to have a filter that excludes IP address or ports?
e.g. --where "ip != 1.1.1.1"

**Comment by davidmcgrew** [comment]
Good idea.   It would also be nice to have a case-insensitive match (for HTTP headers anyway), and a wildcard match, like "sa = 192.1618.1.*".    With a wildcard, we could have the convention that "field=*" would match any flow that contains the field, which would actually be useful because some fields are optional.   What do you think?

**Comment by aradford123** [comment]
that would be very helpful.  Are you proposing wildcarding ("sa=192.168.*.1"), partial match ("sa=192.168.82") or both?

**Comment by davidmcgrew** [comment]
I was thinking of just wildcarding, since it can be used to do a bunch of partial-match like things.   

I think the simplest thing to do would be to replace the '=' operator call with a call to the fnmatchcase() function from https://docs.python.org/2/library/fnmatch.html.   That would support the wildcard operator, plus a ? single-character operator and [] character sets.    

Alternatively, we could add in regular expression matching, but that's more complex and less intuitive (to me at least, and I think to many other people :-)

**Comment by davidmcgrew** [comment]
The sleuth --where option now supports the syntax "da~192.168.*", in which the tilde (~) is the "not equal to" operator, and the star symbol (*) is a wildcard.  

This issue should have been closed long ago - the changes have been around a long time.
