### ISSUE TITLE
Interfaces are named differently from Joy's perspective

### ISSUE THREAD

**Issue by JohnOmernik** [cisco/joy#111]
When running ifconfig, I get a list of interfaces that include lo0, eno0, docker0, lots of other interfaces, however, when I pick one, and try to run joy on it, I get "interface not found" (eno1).  And then it lists the interfaces all as intf1-intf19 so there isn't a correlation between how linux shows the interfaces and joy accesses them. This seems odd from a programatic/administration perspective. 

I.e. to guess which interface, I had to find the one with the proper IP. For some non-communications interfaces, they may not have IPs so how would I actually select the right one (except guess and check?)

**Comment by brilong** [comment]
Could you specify which Linux distribution you are running?  We have only tested on CentOS 7 and Ubuntu 16.04.  There has been limited verification on Debian.

**Comment by JohnOmernik** [comment]
I am running Ubuntu 16.04 but running it within Docker and privileged mode (with Host Networking)

**Comment by brilong** [comment]
Do you mean your container base operating system is Ubuntu 16.04 but you're running joy by itself in a privileged Docker container?

**Comment by JohnOmernik** [comment]
In my case, the host operating system is Ubuntu 16.04, and the container base images (that I start with) is also Ubuntu 16.04.   So all that is Ubuntu. Then I am running joy in the container built FROM ubuntu:16.04 and adding all all the things. (It works, just that the interfaces don't line up, which is odd, because I am running in privileged more AND host mode, and when in the container, ifconfig shows the properly named interfaces...

**Comment by bhudson33** [comment]
John,

We purposely gave every interface a ‘simple symbolic name’. Many operating systems name the interface devices very differently. In some instances the interface names are ridiculously long and complicated (i.e windows server 2012 VM). In order to simplify the interfaces across all operating systems, we moved to a model of using libpcap to find and then name the interfaces. This works the same across all interfaces. If you want to see what interface corresponds to the “joy symbolic name” simply start joy in live capture mode and the interfaces it detects are dumped out as the very first output data to the screen. You can then associate whatever IP/interface you are interested in to the symbolic name.

Cheers,
Bill.

The ’S’ in ‘IoT’ stands for Security.



On Sep 25, 2017, at 10:58 AM, John Omernik <notifications@github.com<mailto:notifications@github.com>> wrote:


When running ifconfig, I get a list of interfaces that include lo0, eno0, docker0, lots of other interfaces, however, when I pick one, and try to run joy on it, I get "interface not found" (eno1). And then it lists the interfaces all as intf1-intf19 so there isn't a correlation between how linux shows the interfaces and joy accesses them. This seems odd from a programatic/administration perspective.

I.e. to guess which interface, I had to find the one with the proper IP. For some non-communications interfaces, they may not have IPs so how would I actually select the right one (except guess and check?)

**Comment by JohnOmernik** [comment]
Right but what if you are using a capture interface that is not assigned an IP? The way it dumps interfaces it shows the interface assignment and the IP address, not all capture cards will be assigned IP addresses. In fact, consider a "sensor" server, where there are multiple interfaces dedicated to ONLY promisc sensor work.   How would we identify the interface without an IP address? Could it print the OS name as well? or accept OS name and if found use that? 

I.e. if I specify eno1 as my interface, it could dump the list and see which of it's interfaces matches eno1 and use that ... right? or am I over simplifying?

**Comment by brilong** [comment]
The operating system interface names are now used in joy configuration.  There is also a new show_interfaces=1 CLI option (set to 0 by default).  Please try it out.
