### ISSUE TITLE
Client key length

### ISSUE THREAD

**Issue by simonstruk** [cisco/joy#124]
Hello,
when joy parses TLS client key exchange message, it includes the length information about the key in the key itself. So if I have a 256 byte RSA premaster secret in my pcap, the clientKeyExchange field will start with 0x0100 and the tls_client_key_length will have the value 2064 instead of 2048. I'm not sure if this is desirable behavior.

**Comment by fliphil** [comment]
Thanks for communicating this. We'll take a look and get back to you!

**Comment by fliphil** [comment]
The length is slightly larger because the software is grabbing the ClientKeyExchange header length at tls.c:465. The reason why we initially went with that value is because the format between different algorithms (RSA, DH, etc.) may be inconsistent. Looking around a bit, I don't see any clear specification detailing the formats for the CKE message. Do you know of some resource(s) that communicate that information?

For now, I think this is probably low priority considering the current list of to-do items for the team.
What are your thoughts?
