### ISSUE TITLE
How to extract a field in an array?

### ISSUE THREAD

**Issue by aradford123** [cisco/joy#40]
I would like to be able to extract select fields from within an array. 

For example, the following dns response.
{  "dns":  [{"rn": "pool.ntp.org", "rr": [{"a": "192.168.10.17", "ttl": 35}, {"a": "192.168.12.251", "ttl": 35}, {"a": "192.168.12.251", "ttl": 35}

--select "dns[].rr[].a"
would extract all of the "a" records from the dns response.

**Comment by davidmcgrew** [comment]
Totally agree.  As I see it, there are three options for what the output would look like in the case of nested objects; please let me know which makes more sense for you.

1.  One alternative would be to "flatten" the object, but give the elements names that reflect the nesting and the array position, like this:
{ "dns.rr[0].a": "192.168.10.17", "dns.rr[1].a": "192.168.12.251", "dns.rr[2].a": "192.168.12.251" }

2.  Yet another option would be to "flatten" the object into a single array:
{ "dns.rr[].a": [ "192.168.10.17",  "192.168.12.251", "192.168.12.251" ] }

3.  Another option would be to leave the object-nesting alone, but strip out all elements other than the selected element and its parents, so that the output looks like this:
{ "dns": [{"rr": [{"a": "192.168.10.17"}, {"a": "192.168.12.251"}, {"a": "192.168.12.251"} ]}

I would guess that option 2 would be most useful, though option 3 might be nice because any python code that can handle the actual object would work on the "stripped" object as well.  

Thanks for your input!

**Comment by bhudson33** [comment]
FWIW, I like option 3 for the simple fact that the parser wouldn’t need to change anything even when filtered.

Cheers,
Bill.

On Mar 19, 2017, at 8:53 AM, David McGrew <notifications@github.com<mailto:notifications@github.com>> wrote:


Totally agree. As I see it, there are three options for what the output would look like in the case of nested objects; please let me know which makes more sense for you.

  1.  One alternative would be to "flatten" the object, but give the elements names that reflect the nesting and the array position, like this:
{ "dns.rr[0].a": "192.168.10.17", "dns.rr[1].a": "192.168.12.251", "dns.rr[2].a": "192.168.12.251" }

  2.  Yet another option would be to "flatten" the object into a single array:
{ "dns.rr[].a": [ "192.168.10.17", "192.168.12.251", "192.168.12.251" ] }

  3.  Another option would be to leave the object-nesting alone, but strip out all elements other than the selected element and its parents, so that the output looks like this:
{ "dns": [{"rr": [{"a": "192.168.10.17"}, {"a": "192.168.12.251"}, {"a": "192.168.12.251"} ]}

I would guess that option 2 would be most useful, though option 3 might be nice because any python code that can handle the actual object would work on the "stripped" object as well.

Thanks for your input!

**Comment by aradford123** [comment]
Thanks David,

I agree with Bill, I would likely have some other process post this, so creating a python dict would make it easier for python (or other tools) to parse.

Adam

**Comment by davidmcgrew** [comment]
Closed out this issue; option #3 was implemented many months ago.
