### ISSUE TITLE
How joy merging UDP packets in a flow

### ISSUE THREAD

**Issue by arunmir** [cisco/joy#68]
Hi,
I'm working using Joy to analyse udp streams (Specially traffic like NTP).
I found that, joy is merging multiple UDP packets into few record entries.

In my case I had 6 packets as shown follows
<img width="1321" alt="screen shot 2017-07-25 at 1 02 01 pm" src="https://user-images.githubusercontent.com/22003582/28554122-02b76f6e-713b-11e7-8c50-18f1de81600b.png">

But I got only 3 records like this.
<img width="949" alt="screen shot 2017-07-25 at 12 59 50 pm" src="https://user-images.githubusercontent.com/22003582/28553975-fe77eaba-7139-11e7-8054-c9a1d536296b.png">

I would like to know on what criteria, joy is merging the UDP packets and is there anyway to write them as individual entries?

**Comment by bhudson33** [comment]
what were the command line parameters you used to invoke joy?

**Comment by arunmir** [comment]
joy tls=1 dns=1 ip_id=1 dist=1 http=1 num_pkts=1  output="./Output.gz" ./161101Amazon.pcap.pcapng

I have attached the pcap file I used below. It has 76 packets totally. But joy generating only 40 records

[161101Amazon.pcap.pcapng.zip](https://github.com/cisco/joy/files/1176451/161101Amazon.pcap.pcapng.zip)

**Comment by bhudson33** [comment]
We believe this to be the intended behavior. In your PCAP, there are ~9 unique 5-tuples. In a perfect world you would only see ~9 Joy flow records. However, due to the inactive timeout, new flows get created with the same 5-tuple. This means that the number of flows should vary somewhere between 9 and total packets of 76 based on the inactive timeout. What we see based on the PCAP is 40 Joy flows which seems about right when taking the inactive timeout into account. Hopefully, this explains what you are seeing.

**Comment by arunmir** [comment]
Ok, I got it. Thank you very much.
I wonder, is there any way to change/disable the the inactive timeout period in JOY?

**Comment by bhudson33** [comment]
you could play with the default values defined in p2f.c and maybe get some values that will produce whatever it is you are looking for. Look around line 290 and you will see the definitions for the inactive and active timeouts.

**Comment by davidmcgrew** [comment]
You could also try out the ./joyq --stitch option

David
