### ISSUE TITLE
a bug submit

### ISSUE THREAD

**Issue by flowsand88** [cisco/joy#90]
line 1668-1684 in p2f.c is not needed, since line 1628 has do the same thing.

some segment fault show when i set "dns=1",some one can help me ?
in wireshark when it parse a dns protocal may cause problem like "name contains a pointer that loops". when this condition appeared, in this project since it use a  recursion to parse dns answer, it cause a segment fault. suggest to solve this bug.

**Comment by fliphil** [comment]
For the redundant code in this case, can you submit a pull request that removes it? In the future for issues that you know how to fix instead of asking us to make the change, please submit a pull-request because Github is a tool for collaboration by the community.

If you are running into a segmentation fault, then I suggest that you change -O3 to -O0 in src/Makefile, rebuild, and then run through GDB or your favorite debugger. Then you can step through the code and see exactly where the seg fault is happening and try to figure out why.

**Comment by flowsand88** [comment]
thanks fliphil
